# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start', models.TimeField(verbose_name='start time')),
                ('stop', models.TimeField(verbose_name='stop time')),
                ('user', models.CharField(max_length=200, verbose_name='user')),
                ('task', models.CharField(max_length=200, verbose_name='task')),
            ],
        ),
    ]
